% this script was writte to assemble the cross-correlations generated from
% the python code getCrossCorr.ipynb
% we generate only cross-corr pairs

clear; %close all;
addpath('C:\Users\soume\Dropbox\EinsteinTelescopeSurvey\DataAnalysisPassive1\');
addpath('C:\Users\soume\Dropbox\EinsteinTelescopeSurvey\TerzietBigSurvey1\FTAN');

%dataPath = 'B:\LimburgBigSurvey1CC-Pair\';
dataPath = 'D:\LimburgSurvey1CC\stack\';
%dataPath = 'D:\ETSurvey1a\';
%% SubArray S0
% stnList = ["WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%    "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";"YDK3A"]; % top left corner
% adding a few more stations
% stnList = ["WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%    "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";...
%    "YDK3A";"YGKGA";"YHKVA";"W4L7A";"XAL4A";"XELYA";"XXLUA";"X1LUA"]; % improved low-freq resolution
%% subArray S01
% stnList = ["0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%    "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%    "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA"];
%% subArray S01B, removing forest nodes
% stnList = ["0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";...
%    "0RPXA";"09PQA";"1PO5A";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%    "0QO3A";"0GO1A";"0POKA";"1EOGA";"03OMA"];
%%
%stnList = ["X6NQA";"X7ORA";"Y0NZA";"Y3OLA";"YAOTA";"YEOMA";...
%    "YGNCA";"YHNNA";"YKNVA";"YLNBA";"YLOWA";"YONYA";"YRNEA";...
%    "YRNVA";"YSOJA";"YUNJA";"YUNZA";"YUOZA";"YXN9A";"YXOQA"];

% stnList = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";...
%     "Z2P2A";"Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";...
%     "ZPPZA";"ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA"];

%stnList = ["ZROJA";"ZYOMA";"ZXOSA";"ZQO1A";"Z3O2A";"ZZPAA";"ZRPCA";...
%    "ZCOUA";"ZIORA";"ZGPDA"];

%stnList = ["0INXA";"0PNVA";"0XNZA";"0GNUA";"0GNDA";"0QNIA";"0ZNEA";...
%    "0PM7A";"0IM0A";"0POKA";"03OMA";"1EOGA";"1ANPA";"1BM8A";"1BMMA"];

%stnList = ["Z2MDA";"Z2NAA";"0PNVA";"0XNZA";"1ANPA";"1BM8A";"0ULZA";...
%    "0FL9A";"ZSMIA"];
%% subArray S02, on top of S03
% stnList = ["ZCM4A";"Y4NCA";"YUNJA";"YRNEA";"YRNVA";"YUNZA";"Y0NZA";...
%    "YXN9A";"YSOJA";"YXOQA";"Y3OLA";"ZCOUA";"ZIORA";"ZQO1A";"ZXOSA";...
%    "ZYOMA";"ZROJA";"ZZN8A";"ZVN3A";"ZXNKA";"ZLNPA";"ZQNFA"];
%% subArray S02 and S12
% stnList = ["ZCM4A";"Y4NCA";"YUNJA";"YRNEA";"YRNVA";"YUNZA";"Y0NZA";...
%     "YXN9A";"YSOJA";"YXOQA";"Y3OLA";"ZCOUA";"ZIORA";"ZQO1A";"ZXOSA";...
%     "ZYOMA";"ZROJA";"ZZN8A";"ZVN3A";"ZXNKA";"ZLNPA";"ZQNFA";...
%     "0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA"];
%% subArray S04
% stnList = ["XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";"Y0KWA";"Y8KWA";...
%     "ZDK2A";"ZOKUA";"ZUJ5A"];
%% subArray S00 and S04
% stnList = ["W1KLA";"W1LKA";"W3JWA";"W8KFA";"WUJ2A";"X0K9A";"X2KQA";...
%     "XBKUA";"XDLDA";"XHKAA";"XUKKA";"XUKWA";"XYKJA";"Y0KWA";"Y8KWA";...
%     "YDK3A";"YGKGA";"YHKVA";"ZDK2A";"ZOKUA";"ZUJ5A"];
%% subArray 00, 04, 13
% stnList = ["W1KLA";"W1LKA";"W3JWA";"W8KFA";"WUJ2A";"X0K9A";"X2KQA";...
%     "XBKUA";"XDLDA";"XHKAA";"XUKKA";"XUKWA";"XYKJA";"Y0KWA";"Y8KWA";...
%     "YDK3A";"YGKGA";"YHKVA";"ZDK2A";"ZOKUA";"ZUJ5A";...
%     "W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%      "XVMMA";"X6M2A";"XVM7A";"XPM9A";"XHNAA";"XZNCA";];
%% subArray S00 and S04 and S05
% stnList = ["XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";"Y0KWA";"Y8KWA";...
%      "ZDK2A";"ZOKUA";"ZUJ5A";"WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%    "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";"YDK3A";...
%    "0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%      "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA"];
%% subArray S05, S11, S12
% stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%      "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";...
%      "0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%     "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA"];
%% subArray S01 S03
% stnList = ["0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%     "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%     "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"0CO6A";"0CPUA";"0GO1A";...
%     "Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";"Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";...
%     "ZGPVA";"ZIORA";"ZPPZA";"ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";...
%     "ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A"];
%% subarray 01, 03 and 12
% stnList = ["0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%     "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%     "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"0CO6A";"0CPUA";"0GO1A";...
%     "Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";"Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";...
%     "ZGPVA";"ZIORA";"ZPPZA";"ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";...
%     "ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
%     "0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA"];
%% subarray S09, S06, S02, S03, S01, S15, 
% stnList = ["YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%      "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%      "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%      "ZLNPA";"ZCM4A";"YYMLA";"Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%       "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%       "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%       "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";"0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%      "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%      "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
%      "0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%      "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%      "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"ZZN8A";"ZVN3A";"ZXNKA";...
% "Z2NAA";"X3O0A";"X7PFA";"YCPBA";"YIPMA";"YOPFA";"YFPTA";"YUP2A";...
%      "Y8PQA";"Y7PAA";"Y3O5A";"Y3OLA";"YSOJA";"YXOQA";"YUOZA";"YLOWA";...
%      "YEOMA";"YAOTA";"X7ORA";"YEL9A";"X4MBA";"XXLUA";"X1LUA";"YHLWA"];
%% .subArray for the fundamental pick analysis
% subarray S09, S06, S02, S03, S01, S15, 
% stnList = ["YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%      "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%      "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%      "ZLNPA";"ZCM4A";"YYMLA";"Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%       "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%       "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%       "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";"0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%      "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%      "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
%      "0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%      "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%      "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"ZZN8A";"ZVN3A";"ZXNKA";...
% "Z2NAA";"X3O0A";"X7PFA";"YCPBA";"YIPMA";"YOPFA";"YFPTA";"YUP2A";...
%      "Y8PQA";"Y7PAA";"Y3O5A";"Y3OLA";"YSOJA";"YXOQA";"YUOZA";"YLOWA";...
%      "YEOMA";"YAOTA";"X7ORA";"YEL9A";"X4MBA";"XXLUA";"X1LUA";"YHLWA";...
%      "W5NUA";"XHNLA";"XVNMA";"XZNCA";"XLN1A";"XTNZA";"W7N9A";"XON9A";...
%      "XDOGA";"XOOIA";"XTOIA";"XAOYA";"XNOYA";"XQO5A";"XGPDA";"XIPOA";...
%      "XPPNA";"XKPSA";"XYPWA";"YAP0A";"X3QDA";"X5QHA";"YAQGA";"YAQEA";...
%      "YCQGA";"YHP8A";"YJQBA";"YIQEA";"YKQHA";"YNP9A";"ZILIA";"ZRLWA";...
%      "Z2MDA";"ZSMIA";"0IM0A";"0GNDA";"0PM7A";"0QNIA";"0XNZA";"0PNVA";...
%      "0INXA";"0GNUA";"0ZNEA";"1ANPA";"0FL9A";"X0K9A";"YDK3A";"XFRFA";...
%      "W2RAA";"W3QZA";"WKQQA";"W4QGA";"XPQJA";"W7PSA"];
%% subArray S13, S16
% stnList = ["W4L7A";"XAL4A";"XELYA";"W9MRA";"XFMHA";"XMMBA";"XFMWA";...
%     "XVMMA";"XHNAA";"XPM9A";"XVM7A";"XZNCA";"W5NUA";"XHNLA";"XVNMA";"X6NQA";...
%     "W7N9A";"XLN1A";"XTNZA";"XDOGA";"XON9A";"XOOIA";"XTOIA";"XAOYA";...
%     "XNOYA";"XGPDA";"XQO5A";"X3O0A";"X7ORA";"YAOTA";"YEOMA";"WUJ2A";"W3JWA";...
%     "W1KLA";"XBKUA";"XUKKA";"XDLDA";"W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";...
%     "XYKJA";"X2KQA";"YDK3A"];
%% S05 subarray
% stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%     "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";"Z2MDA";"0FL9A";"0ULZA"];%S05

% SO5Full (+closely spaced sensors at Meleschet)
% stnList = ["Z2MDA";"0FL9A";"0ULZA";"0GK6A";"Z8LHA";"ZRLWA";"ZILIA";...
%   "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";"Y6MAA";...
%   "Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];

%stnList = ["Z2KWA";"0GK6A";"Z6KQA";"ZUJ5A"];%S005
%stnList = ["Z2KWA";"ZOKUA";"ZDK2A";"ZILIA";"ZRLWA";"Z8LHA"]; %S0005
%% subArray S04 and S05
% stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%     "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";...
%     "Z2MDA";"0FL9A";"0ULZA";"XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";...
%     "Y0KWA";"Y8KWA";"ZDK2A";"ZOKUA";"ZUJ5A"];

%% subArray S05, S11, S12
% stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%      "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";...
% "Y0KWA";"Z2MDA";"0FL9A";"0ULZA";"0ULZA";"0FL9A";"Z2MDA";...
% "Z2NAA";"0GNDA";"0IM0A";"0PM7A";"0QNIA";"0ZNEA";"1BM8A";...
% "1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA";"0IM0A";...
% "Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA"];
%% subArray S05, S11, S12, S01
% stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%      "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";...
% "Y0KWA";"Z2MDA";"0FL9A";"0ULZA";"0ULZA";"0FL9A";"Z2MDA";...
% "Z2NAA";"0GNDA";"0IM0A";"0PM7A";"0QNIA";"0ZNEA";"1BM8A";...
% "1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA";"0IM0A";...
% "Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA";"0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%     "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%     "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA"];
%% subArray 05 09
stnList = ["0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";"Z2KWA";"Z6KQA";...
    "ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";"Z2MDA";"0FL9A";"0ULZA";...
    "Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
     "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
     "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
     "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";"ZSMIA"];
%% subArray 00, 04, 05, 11
% stnList = ["XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";"Y0KWA";"Y8KWA";...
%       "ZDK2A";"ZOKUA";"ZUJ5A";"WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%     "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";"YDK3A";...
%     "0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%       "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";...
%       "0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%     "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA"];
%% subArray HighFeb 00, 04, 05
% stnList = ["XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";"Y0KWA";"Y8KWA";...
%       "ZDK2A";"ZOKUA";"ZUJ5A";"WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%     "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";"YDK3A";...
%     "0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%       "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";...
%       "0ULZA";"0FL9A";"Z2MDA";"ZSMIA"];
%% stn list for FundApril analysis

% stnList = [["03OMA";"03PAA";"08P9A";"08QLA";"09PQA";"0CO6A";...
%     "0CPUA";"0FL9A";"0GK6A";"0GNDA";"0GNUA";"0GO1A";"0IM0A";...
%     "0INXA";"0KP6A";"0NQPA";"0PM7A";"0PNVA";"0POKA";"0PPFA";...
%     "0QNIA";"0QO3A";"0RPXA";"0ULZA";"0UO6A";"0XNZA";"0XPIA";...
%     "0ZNEA";"0ZQEA";"1ANPA";"1BM8A";"1BMMA";"1EOGA";"1MP1A";...
%     "1OP6A";"1PO5A";"W1KLA";"W1LKA";"W3JWA";...
%     "W4L7A";"W5NUA";"W7N9A";"W8KFA";"W9MRA";...
%     "WUJ2A";"X0K9A";"X1LUA";"X2KQA";"X3O0A";"X3QDA";...
%     "X4MBA";"X5QHA";"X6M2A";"X6NQA";"X7ORA";"X7PFA";"XAL4A";...
%     "XAOYA";"XBKUA";"XDLDA";"XDOGA";"XELYA";"XFMHA";"XFMWA";...
%     "XGPDA";"XHKAA";"XHNAA";"XHNLA";"XIPOA";"XKPSA";...
%     "XLN1A";"XMMBA";"XNOYA";"XON9A";"XOOIA";"XPM9A";"XPPNA";...
%     "XQO5A";"XTNZA";"XTOIA";"XUKKA";"XUKWA";"XVM7A";...
%     "XVMMA";"XVNMA";"XXLUA";"XYKJA";"XYPWA";"XZNCA";"Y0KWA";...
%     "Y0MBA";"Y0NZA";"Y3O5A";"Y3OLA";"Y4NCA";"Y6MAA";"Y7L9A";...
%     "Y7L9B";"Y7PAA";"Y8KWA";"Y8L6A";"Y8L8A";"Y8MAA";"Y8PQA";...
%     "Y9L7A";"YAOTA";"YAP0A";"YAQEA";"YAQGA";"YCPBA";"YCQGA";...
%     "YDK3A";"YEL9A";"YEOMA";"YFPTA";"YGKGA";"YGMXA";"YGNCA";...
%     "YHKVA";"YHLWA";"YHNNA";"YHP8A";"YIPMA";"YIQEA";"YJQBA";...
%     "YKNVA";"YKQHA";"YLMPA";"YLNBA";"YLOWA";"YNP9A";"YONYA";...
%     "YOPFA";"YRNEA";"YRNVA";"YSOJA";"YUNJA";"YUNZA";"YUOZA";...
%     "YUP2A";"YXN9A";"YXOQA";"YYMLA";"Z2KWA";"Z2MDA";"Z2NAA";...
%     "Z2P2A";"Z3O2A";"Z5PHA";"Z6KQA";"Z6PPA";"Z8LHA";"ZBMKA";...
%     "ZCM4A";"ZCOUA";"ZDK2A";"ZGPDA";"ZGPVA";"ZILIA";"ZIORA";...
%     "ZLNPA";"ZOKUA";"ZPPZA";"ZQNFA";"ZQO1A";"ZRLWA";"ZROJA";...
%     "ZRPCA";"ZSMIA";"ZUJ5A";"ZVN3A";"ZXNKA";"ZXOSA";"ZYOMA";...
%     "ZZN8A";"ZZPAA"]];

%% subArray 00, 04, 05, 11, 13B
% stnList = ["XYKJA";"YGKGA";"X2KQA";"YHKVA";"YDK3A";"Y0KWA";"Y8KWA";...
%        "ZDK2A";"ZOKUA";"ZUJ5A";"WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%      "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";"YDK3A";...
%      "0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Y8L6A";...
%        "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";...
%        "0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%      "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA";...
% "W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%      "XVMMA";"X6M2A";"XVM7A";"XPM9A";"XHNAA";"XZNCA"];
%% subArray S06
% stnList = ["YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%    "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%    "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%    "ZLNPA";"ZCM4A";"YYMLA"];%S06

%% subArray S06B
% stnList = ["YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%     "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";...
%     "YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";];
%% subArray S06C
% stnList = ["YGNCA";"YHNNA";"YKNVA";"YONYA";"YUNZA";"YXN9A";"YSOJA";"YEOMA";...
%     "X7ORA";"YAOTA";"XTOIA";"XOOIA";"XON9A";"XTNZA";"XLN1A";"XVNMA";...
%     "XZNCA";"X6NQA";"XHNLA"];
%% analyzing SO3 subarray better
%stnList = ["ZYOMA";"ZXOSA";"ZQO1A";"ZRPCA";"ZZPAA";"Z3O2A";"0CO6A";...
%    "Z5PHA";"0GO1A"];
% stnList = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%    "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%    "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A"];
%% subArray 03 and 15
% stnList = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%     "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%     "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
%     "X3O0A";"X7PFA";"YCPBA";"YIPMA";"YOPFA";"YFPTA";"YUP2A";...
%      "Y8PQA";"Y7PAA";"Y3O5A";"Y3OLA";"YSOJA";"YXOQA";"YUOZA";"YLOWA";...
%      "YEOMA";"YAOTA";"X7ORA"];
%% subArray 06 and 03
% stnList = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%     "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%     "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
% "YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%     "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%     "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%     "ZLNPA";"ZCM4A";"YYMLA"];
%% subArray S06 S03 S02
% stnList = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%     "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%     "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA";"0KP6A";"0RPXA";"0PPFA";"0QO3A";...
% "YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%     "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%     "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%     "ZLNPA";"ZCM4A";"YYMLA";"ZCM4A";"Y4NCA";"YUNJA";"YRNEA";"YRNVA";"YUNZA";"Y0NZA";...
%     "YXN9A";"YSOJA";"YXOQA";"Y3OLA";"ZCOUA";"ZIORA";"ZQO1A";"ZXOSA";...
%     "ZYOMA";"ZROJA";"ZZN8A";"ZVN3A";"ZXNKA";"ZLNPA";"ZQNFA"];
%% subArray SO7, near left of Broek
%stnList = ["W5NUA";"W7N9A";"XDOGA";"XOOIA";"XTOIA";"XON9A";"XLN1A";...
%    "W5NUA";"XHNLA";"XTNZA";"XVNMA";"X6NQA";"XZNCA";"XHNAA";"XPM9A";...
%    "XVM7A";"XAOYA";"XNOYA";"XQO5A";"X3O0A";"YAOTA";"YEOMA"];
%% subArray S08
%stnList = ["YGKGA";"YHKVA";"YDK3A";"X2KQA";"X0K9A";"XXLUA";"X1LUA";...
%    "YHLWA";"X4MBA";"YEL9A";"XVMMA";"YGMXA";"YLMPA";"YYMLA";"ZBMKA";...
%    "Y0MBA";"Y8MAA";"ZILIA";"ZDK2A";"Y8KWA";"Y0KWA"];
%% subArray SO8A
% stnList = ["XUKKA";"XYKJA";"X2KQA";"XUKWA";"YGKGA";"YHKVA";"YDK3A";...
%    "X0K9A";"XXLUA";"X1LUA";"YHLWA";"YEL9A";"X4MBA";"YLMPA";"YGMXA";...
%    "X6M2A";"XMMBA";"XVMMA"];
%% subArray S08B
% stnList = ["Y0KWA";"Y8KWA";"ZDK2A";"ZILIA";"ZRLWA";"Z2MDA";"ZSMIA";...
%    "ZBMKA";"YYMLA";"Y0MBA";"Y6MAA";"Y7L9B";"Y8MAA";"Y7L9A";"Y8L8A";...
%    "Y9L7A";"Y8L6A";"YHLWA"];
%% subArray S08C, low velocity target
% stnList = ["XXLUA";"X1LUA";"YHLWA";"YEL9A";"X4MBA";"YLMPA";"YGMXA";...
%     "X6M2A";"XMMBA";"XVMMA";"Y0MBA";"YYMLA";"XVM7A";"XZNCA";"YGNCA";"YLNBA"];
%% S08-FULL
% stnList = ["X0K9A";"X1LUA";"X2KQA";"X4MBA";"X6M2A";"XMMBA";"XUKKA";"XUKWA";...
%    "XVMMA";"XXLUA";"XYKJA";"Y0KWA";"Y0MBA";"Y6MAA";"Y7L9A";"Y7L9B";...
%    "Y8KWA";"Y8L6A";"Y8L8A";"Y8MAA";"Y9L7A";"YDK3A";"YEL9A";"YGKGA";...
%    "YGMXA";"YHKVA";"YHLWA";"YLMPA";"YYMLA";"Z2MDA";"ZBMKA";"ZDK2A";...
%    "ZILIA";"ZRLWA";"ZSMIA"];
%% subArray S08-D, this array does not have the north nodes
% stnList = ["X1LUA";"X4MBA";"X6M2A";"XMMBA";...
%    "XVMMA";"XXLUA";"Y0MBA";"Y6MAA";"Y7L9A";"Y7L9B";...
%    "Y8KWA";"Y8L6A";"Y8L8A";"Y8MAA";"Y9L7A";"YEL9A";...
%    "YGMXA";"YHLWA";"YLMPA";"YYMLA";"Z2MDA";"ZBMKA";"ZDK2A";...
%    "ZILIA";"ZRLWA";"ZSMIA"];
%% combining S08C and S09
% stnList = ["XXLUA";"X1LUA";"YHLWA";"YEL9A";"X4MBA";"YLMPA";"YGMXA";...
%      "X6M2A";"XMMBA";"XVMMA";"Y0MBA";"YYMLA";"XVM7A";"XZNCA";"YGNCA";...
%      "YLNBA";...
%      "Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];
%% S09 is a new array, and includes the Meleschet closely spaced ones
% stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%     "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%     "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%     "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];
% this is S09 without Melleschet
% stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%    "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%    "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y8MAA"];
%% mixing S09 and S05
% stnList = ["Z2MDA";"0FL9A";"0ULZA";"0GK6A";"Z8LHA";"ZRLWA";"ZILIA";...
%    "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";"Y6MAA";...
%    "Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";...
%    "Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];
%% subArray 09 and 06
% stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";...
%      "YGNCA";"YRNEA";"YLNBA";"YUNJA";"YHNNA";"YKNVA";"YONYA";...
%     "YRNVA";"YUNZA";"Y0NZA";"X6NQA";"Y4NCA";"YGMXA";"X6M2A";...
%     "YLMPA";"YXN9A";"YSOJA";"YEOMA";"YLOWA";"YUOZA";"YXOQA";"Y3OLA";...
%     "ZLNPA";"ZCM4A";"YYMLA"];
%% subArray 09 and 18
% stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";...
%      "YUNJA";"YRNEA";"YLNBA";"YGNCA";"YHNNA";"YKNVA";"YONYA";...
%     "YRNVA";"YUNZA";"Y0NZA";"YXN9A";"Y3OLA";"YXOQA";"YSOJA";"YLOWA";...
%     "YEOMA";"YUOZA";"X6NQA";"YAOTA";"X7ORA";"Y4NCA";"ZCOUA";"ZIORA";...
%     "ZROJA";"ZVN3A";"ZLNPA"];
%% subarray 10, this is right of SO9, and includes the Melleschet
% stnList = ["Y0MBA";"YYMLA";"ZBMKA";"ZCM4A";"Y4NCA";"ZLNPA";"ZQNFA";...
%    "ZSMIA";"YLMPA";"YRNEA";"YUNJA";...
%    "Y6MAA";"Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];

% this is S10 but without Melleschet
% stnList = ["Y0MBA";"YYMLA";"ZBMKA";"ZCM4A";"Y4NCA";"ZLNPA";"ZQNFA";...
%    "ZXNKA";"Z2NAA";"ZSMIA";"Z2MDA";"0FL9A";"0IM0A";"0GNDA";"ZRLWA";...
%    "Y6MAA"];
% S10case1
% stnList = ["Y0MBA";"YYMLA";"ZBMKA";"ZCM4A";"Y4NCA";"ZLNPA";"ZQNFA";...
%    "ZXNKA";"Z2NAA";"ZSMIA";"Z2MDA";"0FL9A";"0IM0A";"0GNDA";"ZRLWA";...
%    "Y6MAA";"Y8MAA";"Y8L8A"];

%% subarray 11, ofcourse without Melleschet :P
% stnList = ["0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%    "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA"];

%% mixing subarray 09 and 11
% stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";"ZXNKA";"ZSMIA";...
%      "0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%     "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA"];
%% SubArray 12, overlaps with S11
% stnList = ["0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%    "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%    "0XNZA";"0INXA";"0GNUA"];
%% subArray S01 and S12
% stnList = ["0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%     "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%     "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA"];
%% subArray S01 S12, S11
% stnList = ["0NQPA";"0ZQEA";"08QLA";"08P9A";"1MP1A";"1OP6A";"0KP6A";...
%      "0RPXA";"09PQA";"1PO5A";"0CPUA";"0PPFA";"0XPIA";"03PAA";"0UO6A";...
%      "0QO3A";"0GO1A";"0CO6A";"0POKA";"1EOGA";"03OMA";"0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%      "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%      "0XNZA";"0INXA";"0GNUA";...
%      "0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%     "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA";"1ANPA"];
%% SubArray 12B, overlaps with S11
% stnList = ["0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";...
%    "0PM7A";"0QNIA";"0PNVA";"ZLNPA";"ZQNFA";...
%    "0XNZA";"0INXA";"0GNUA"];
%% SubArray 11 and 12, overlaps with S11
% stnList = ["0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%    "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%    "0XNZA";"0INXA";"0GNUA";"0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%   "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA"];
%% subArray 13, overlaps with S0 and S09
% stnList = ["W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%    "XVMMA";"XXLUA";"X1LUA";"X4MBA";"YEL9A";"YHLWA";"YLMPA";"YGMXA";...
%    "X6M2A";"XVM7A";"XPM9A";"XHNAA"]; % updated March 22, 2022

% stnList = ["W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%     "XVMMA";"X6M2A";"XVM7A";"XPM9A";"XHNAA";"XZNCA";]; % updated March 22, 2022

% stnList = ["XXLUA";"X1LUA";"YHLWA";"YEL9A";"X4MBA";"XVMMA"];
% this we call S13A
% stnList = ["W4L7A";"W9MRA";"XFMWA";"XFMHA";"XAL4A";...
%    "XELYA";"XMMBA";"XVMMA";"X4MBA";"XXLUA";"YHLWA";"YEL9A";...
%    "X1LUA";"XHNAA";"XPM9A";"XVM7A";"XZNCA";"X6M2A";"YGMXA";"YLMPA"];
%% SubArray 13B and 00 together
% stnList = ["W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%     "XVMMA";"X6M2A";"XVM7A";"XPM9A";"XHNAA";"XZNCA";"WUJ2A";"W3JWA";...
%     "W1KLA";"XBKUA";"XUKKA";"XDLDA";"W1LKA";"X0K9A";"XHKAA";"W8KFA";...
%     "XUKWA";"XYKJA";"X2KQA";"YDK3A"];
%% subArray 13B and some added sensors south of it, subarray 28
% stnList = ["W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%      "XVMMA";"X6M2A";"XVM7A";"XPM9A";"XHNAA";"XZNCA";"XHNLA";"XVNMA";...
%      "W5NUA";"XLN1A";"XTNZA";"W7N9A";"XDOGA";"XON9A";"XOOIA";"XTOIA";...
%      "XAOYA";"XNOYA";"XQO5A";"X6NQA";"X3O0A";"X7ORA";"YAOTA";"YEOMA";...
%      "Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%      "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%      "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"Y8MAA";"Y7L9B";...
%      "Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"]; % updated March 22, 2022
%% SubArray 14, near Cottessen
% stnList = ["YCPBA";"X7PFA";"XYPWA";"X3QDA";"YIPMA";"YFPTA";"YAP0A";...
%     "YUP2A";"YOPFA";"X5QHA";"YCQGA";"YKQHA";...
%     "YJQBA";"XPPNA";"XQO5A";"X3O0A";"YLOWA";"YUOZA";...
%     "Y8PQA";"Y7PAA";"YSOJA";"YXOQA";"Y3O5A";"YEOMA";"YAOTA";"X7ORA";...
%     "XGPDA";"XIPOA";"XKPSA"];
% subarray S14A
% stnList = ["YCPBA";"X7PFA";"XYPWA";"X3QDA";"YIPMA";"YFPTA";"YAP0A";...
%      "YUP2A";"YOPFA";"X5QHA";"YCQGA";"YKQHA";...
%      "YJQBA";"YNP9A";"Y8PQA";"Y7PAA";"Y3O5A";"YUOZA";"YLOWA";...
%      "YAOTA";"X3O0A"];
% subArray 14B
% stnList = ["YCPBA";"X7PFA";"XYPWA";"X3QDA";"YIPMA";"YFPTA";"YAP0A";...
%     "YUP2A";"YOPFA";"X5QHA";"YAQGA";"YAQEA";"YCQGA";"YKQHA";"YIQEA";...
%     "YJQBA";"YHP8A";"YNP9A";"XPPNA";"X3O0A";"YAOTA";"X7ORA";"YEOMA";...
%     "YLOWA";"YUOZA"];
%% stations S09Full and S10 is combined here to check if any improvemnets
% low frequency occurs
%stnList = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%    "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%    "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y6MAA";"ZRLWA";"ZSMIA";"Z2NAA";"0GNDA";...
%     "0IM0A";"0FL9A";"Z2MDA";"ZXNKA"];
%% combine arrays S10 and S11, just to check low-freq resolution
%stnList = ["Y0MBA";"YYMLA";"ZBMKA";"ZCM4A";"Y4NCA";"ZLNPA";"ZQNFA";...
%    "ZXNKA";"Z2NAA";"ZSMIA";"Z2MDA";"0FL9A";"0IM0A";"0GNDA";"ZRLWA";...
%    "Y6MAA";"0ULZA";"1BMMA";"1BM8A";"1ANPA";"0XNZA";"0INXA";"0PNVA";...
%    "0QNIA";"0ZNEA";"0PM7A"];
%% subArray S15
% stnList = ["X3O0A";"X7PFA";"YCPBA";"YIPMA";"YOPFA";"YFPTA";"YUP2A";...
%     "Y8PQA";"Y7PAA";"Y3O5A";"Y3OLA";"YSOJA";"YXOQA";"YUOZA";"YLOWA";...
%     "YEOMA";"YAOTA";"X7ORA"];
%% subArray 16, left of S15
% stnList = ["XDOGA";"XAOYA";"XOOIA";"XTOIA";"XNOYA";"XQO5A";"X3O0A";...
%   "YCPBA";"X7PFA";"YIPMA";"YFPTA";"YAP0A";"XYPWA";"XPPNA";"XKPSA";...
%   "XIPOA";"XGPDA";"W7PSA"];
%% adding stations to subArray S16
% stnList = ["XDOGA";"XAOYA";"XOOIA";"XTOIA";"XNOYA";"XQO5A";"X3O0A";...
%   "YCPBA";"X7PFA";"YIPMA";"YFPTA";"YAP0A";"XYPWA";"XPPNA";"XKPSA";...
%   "XIPOA";"XGPDA";"W7PSA";"XON9A";"W7N9A";"X7ORA";"YAOTA";"YEOMA"];

%% subArray S27
% stnList = ["W5NUA";"XHNLA";"XVNMA";"W7N9A";"XLN1A";"XTNZA";"XDOGA";...
%     "XON9A";"XOOIA";"XTOIA";"XAOYA";"XNOYA";"XGPDA";"XQO5A";"X3O0A"];

%% subArray S18, above S15, overlaps with S09 annd S15
% stnList = ["YUNJA";"YRNEA";"YLNBA";"YGNCA";"YHNNA";"YKNVA";"YONYA";...
%    "YRNVA";"YUNZA";"Y0NZA";"YXN9A";"Y3OLA";"YXOQA";"YSOJA";"YLOWA";...
%    "YEOMA";"YUOZA";"X6NQA";"YAOTA";"X7ORA";"Y4NCA";"ZCOUA";"ZIORA";...
%    "ZROJA";"ZVN3A";"ZLNPA"];

% stnList = ["YUNJA";"YRNEA";"YLNBA";"YGNCA";"YHNNA";"YKNVA";"YONYA";...
%  "YRNVA";"YUNZA";"Y0NZA";"YXN9A";"Y3OLA";"YXOQA";"YSOJA";"YLOWA";...
%  "YEOMA";"YUOZA";"X6NQA";"YAOTA";"X7ORA";"Y4NCA";"XZNCA";"XVNMA";...
%  "XTNZA";"XTOIA";"XQO5A";"XNOYA";"XVM7A";"XPM9A";"XHNAA";"XHNLA";...
%  "XLN1A"];
%% subArray 19, near Terziet
% stnList = ["WKQQA";"W3QZA";"W2RAA";"XFRFA";"W4QGA";"XPQJA";"W7PSA";...
%    "XKPSA";"XGPDA";"XIPOA";"XPPNA";"XYPWA";...
%    "XYPWA";"X3QDA";];

%% subArray 20, this bridges gap between S12, S02, S03
% stnList = ["ZQNFA";"ZXNKA";"Z2NAA";"0GNDA";"0QNIA";"0PNVA";"0INXA";...
%     "0GNUA";"ZZN8A";"ZVN3A";"ZROJA";"ZYOMA";"ZXOSA";"Z3O2A";"0CO6A";...
%     "0GO1A";"0POKA";"0XNZA";"03OMA";"ZLNPA";"0IM0A";"Z2NAA";"ZXNKA";"0GNDA";"ZVN3A";"ZZN8A";"0POKA";...
%     "03OMA";"1EOGA";"1ANPA";"1BM8A";"0ZNEA";"0PM7A";"0QNIA";"0PNVA";...
%     "0XNZA";"0INXA";"0GNUA"];

%% doing the Melleschet array; with just 3 sensors out in south
%stnList = ["YYMLA";"ZBMKA";"Y0MBA";"Y6MAA";"Y8MAA";"Y7L9B";"Y8L8A";...
%   "Y8L6A";"Y9L7A";"Y7L9A"];
%stnList = ["YGNCA";"YHNNA";"YKNVA";"YONYA";"YRNVA";"YUNZA";"YUNJA";...
%    "YRNEA";"YLNBA"];
%% subArray 101
%stnList = ["YEOMA";"YLOWA";"YUOZA";"YOPFA";"YCPBA";"X3O0A";"YAOTA";...
%    "X7ORA";"X7PFA"];
%% subArray within S13, 102
%stnList = ["W4L7A";"XAL4A";"XELYA";"W9MRA";"XFMHA";"XMMBA";"XFMWA";...
%    "XVMMA";"XHNAA";"XPM9A";"XVM7A"];
%% subArray withon S17, 103
%stnList = ["W7N9A";"XDOGA";"XOOIA";"XON9A";"XLN1A";"XHNLA";"W5NUA";...
%    "XTOIA"];
%% subArray within S13, 104
%stnList = ["Y0KWA";"Y8KWA";"ZDK2A";"ZILIA";"ZRLWA";"ZSMIA";"ZBMKA";...
%    "Y0MBA";"YYMLA";"Y8MAA";"Y8L8A";"Y9L7A";"Y6MAA";"Y7L9B";"Y8L6A";...
%    "Y7L9A";"Z2MDA"];
%% Melleschet array
%stnList = ["Y6MAA";"Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";...
%    "Y0MBA"];
%% subArray within S0, right part of it, 106
%stnList = ["XUKKA";"XYKJA";"XUKWA";"X2KQA";"X0K9A";"YDK3A";"YHKVA";...
%    "YGKGA"];
%% subArray left of S0
%stnList = ["WUJ2A";"W3JWA";"W1KLA";"W8KFA";"XHKAA";"XBKUA"];
%% subArray 21
% stnList = ["WKQQA";"W3QZA";"W2RAA";"XFRFA";"W4QGA";"XPQJA";"W7PSA";...
%     "XIPOA";"XKPSA";"XPPNA";"XYPWA";"YAP0A";"YFPTA";"YNP9A";"YHP8A";...
%     "YJQBA";"YIQEA";"YKQHA";"YCQGA";"YAQEA";"YAQGA";"X3QDA";"X5QHA"];
% %% subArray 24
% stnList = ["XGPDA";"XIPOA";"XKPSA";"XPPNA";"XNOYA";"XQO5A";"X3O0A";...
%     "YCPBA";"X7PFA";"YIPMA";"YFPTA";"YAP0A";"XYPWA"];
%% subArray 25
% stnList = ["YCPBA";"X7PFA";"XYPWA";"YOPFA";"YIPMA";"YFPTA";...
%     "YAP0A";"X3QDA";"YUP2A";"YNP9A";"YHP8A";"YJQBA";"YKQHA";...
%     "YIQEA";"YCQGA";"YAQEA";"YAQGA";"X5QHA"];
%% subArray 26
% stnList = ["W5NUA";"XHNLA";"XVNMA";"XLN1A";"XTNZA";"W7N9A";"XNOYA";...
%     "XDOGA";"XOOIA";"XTOIA";"XAOYA";"XON9A";"XQO5A";"X3O0A";"YAOTA";...
%     "X7ORA"];
%%
% trying small arrays now, to avoid heterogenity small1
%stnList = ["YGNCA";"YHNNA";"YKNVA";"YONYA";"YUNZA";"Y0NZA";"YRNVA";...
%    "YLNBA";"YRNEA";"YUNJA"];

% trying the array near Restaurand Buitenlust, small2
%stnList = ["X3O0A";"YCPBA";"YLOWA";"YEOMA";"YAOTA";"X7ORA";"YOPFA";"YUOZA";...
%    "YXOQA";"YSOJA"];

% a small array near Vakantie Vocken, that was super high velocity
%stnList = ["XON9A";"XOOIA";"XTOIA";"XTNZA";"XLN1A"];

% small array near Oud Bommerich
%stnList = ["XHNAA";"XPM9A";"XVM7A";"XZNCA";"XHNLA";"XVNMA";"XTNZA";...
%    "XLN1A"];

% another small array near HGN station
%stnList = ["W7PSA";"XIPOA";"XKPSA";"XGPDA";"XPPNA"];

% trying a small array within S13a, that was not very clear%
%stnList = ["X6M2A";"YGMXA";"YLMPA";"YEL9A";"X4MBA";"XVMMA";"XXLUA";...
%    "X1LUA";"YHLWA"];

% so now i try one with Melleschet, almost half of S13a
%stnList = ["Y6MAA";"Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A";...
%    "Y0MBA";"YYMLA";"YLMPA";"YHLWA";"YEL9A";"YGMXA";"X1LUA";"X4MBA";...
%    "XXLUA";"XMMBA";"XVMMA";"X6M2A";"XUKKA";"XUKWA";"X0K9A";"XYKJA";...
%    "X2KQA";"YDK3A";"YHKVA";"YGKGA"];

% another small array within S0
%stnList = ["XUKKA";"XUKWA";"X0K9A";"XYKJA";"X2KQA";"YDK3A";...
%    "YHKVA";"YGKGA"]; % this is alright

% another small array left small6 array and within S13
%stnList= ["W4L7A";"XAL4A";"XMMBA";"XFMHA";"XELYA";"W9MRA";"XFMWA";...
%    "XVMMA";"XXLUA";"X1LUA";"X4MBA";"YEL9A";"YHLWA";"YLMPA";"YGMXA";...
%    "X6M2A";"XVM7A";"XPM9A";"XHNAA"];% small11 name

% another small array right of Epn
%stnList = ["W5NUA";"XHNLA";"XLN1A";"W7N9A";"XDOGA";"XON9A";"XTOIA";...
%    "XOOIA";"XNOYA";"XAOYA";"X6NQA";"X7ORA";"YEOMA";"X3O0A";"XGPDA";...
%    "XQO5A";"YAOTA"];

%stnList = ["XXLUA";"XMMBA";"XVMMA";"X6M2A";"YGMXA";"YLMPA";"YEL9A";...
%    "YHLWA";"X1LUA";"X4MBA"];

%stnList = ["XDOGA";"0FL9A"];
%%
% stnListA = ["YUNJA";"YRNEA";"YLNBA";"YGNCA";"YHNNA";"YKNVA";"YONYA";...
%   "YRNVA";"YUNZA";"Y0NZA";"YXN9A";"Y3OLA";"YXOQA";"YSOJA";"YLOWA";...
%   "YEOMA";"YUOZA";"X6NQA";"YAOTA";"X7ORA";"Y4NCA"]; % S18
% stnListB = ["Y0MBA";"YYMLA";"YLMPA";"YGMXA";"ZBMKA";"ZCM4A";...
%    "Y4NCA";"Y0NZA";"YUNZA";"YONYA";"YKNVA";"YRNVA";"YHNNA";"YGNCA";...
%    "YLNBA";"YRNEA";"YUNJA";"ZLNPA";"ZQNFA";"Y8MAA"];% this is S09
% stnListC = ["0CO6A";"0CPUA";"0GO1A";"Y3O5A";"Y7PAA";"Y8PQA";"Z2P2A";...
%    "Z3O2A";"Z5PHA";"Z6PPA";"ZCOUA";"ZGPDA";"ZGPVA";"ZIORA";"ZPPZA";...
%    "ZQO1A";"ZROJA";"ZRPCA";"ZXOSA";"ZYOMA";"ZZPAA"];
% stnList = [stnListA;stnListB;stnListC];
% stnList = unique(stnList);
%%
% stnListA = ["Y0MBA";"YYMLA";"ZBMKA";"ZCM4A";"Y4NCA";"ZLNPA";"ZQNFA";...
%    "ZXNKA";"Z2NAA";"ZSMIA";"Z2MDA";"0FL9A";"0IM0A";"0GNDA";"ZRLWA";...
%    "Y6MAA";"Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"]; % S10
% stnListB = ["0ULZA";"0FL9A";"Z2MDA";"Z2NAA";"0GNDA";"0IM0A";"0PM7A";...
%    "0QNIA";"0ZNEA";"1BM8A";"1BMMA";"0GNUA";"0PNVA";"0XNZA";"0INXA"];
% stnList = [stnListA;stnListB];
% stnList = unique(stnList);
%%
% stnListA = ["WUJ2A";"W3JWA";"W1KLA";"XBKUA";"XUKKA";"XDLDA";...
%     "W1LKA";"X0K9A";"XHKAA";"W8KFA";"XUKWA";"XYKJA";"X2KQA";...
%     "YDK3A";"YGKGA";"YHKVA";"W4L7A";"XAL4A";"XELYA";"XXLUA";"X1LUA"];
% stnListB = ["X0K9A";"X1LUA";"X2KQA";"X4MBA";"X6M2A";"XMMBA";"XUKKA";"XUKWA";...
%     "XVMMA";"XXLUA";"XYKJA";"Y0KWA";"Y0MBA";"Y6MAA";"Y7L9A";"Y7L9B";...
%     "Y8KWA";"Y8L6A";"Y8L8A";"Y8MAA";"Y9L7A";"YDK3A";"YEL9A";"YGKGA";...
%     "YGMXA";"YHKVA";"YHLWA";"YLMPA";"YYMLA";"Z2MDA";"ZBMKA";"ZDK2A";...
%     "ZILIA";"ZRLWA";"ZSMIA"];
%
% stnListC = ["Z2MDA";"0FL9A";"0ULZA";"0GK6A";"Z8LHA";"ZRLWA";"ZILIA";...
%    "Z2KWA";"Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA";"Y6MAA";...
%    "Y8MAA";"Y7L9B";"Y7L9A";"Y8L8A";"Y9L7A";"Y8L6A"];
% stnList = [stnListA;stnListB;stnListC];
% stnList = unique(stnList);
%%
%stnList = ["0XNZA";"0QNIA";"0PNVA";"0INXA";"0GNUA";"0ZNEA";"0PM7A";"0GNDA"];

%stnList = ["YHLWA";"Z2NAA"];

%stnList = ["XUKWA";"X0K9A";"X2KQA";"YDK3A"]; % S0, subArrayTest
%stnList = ["YGNCA";"YHNNA";"YKNVA";"YONYA";"YRNVA";"YUNJA";"YRNEA";"YLNBA"];% S1
%stnList = ["XMMBA";"XFMHA";"XVMMA";"W9MRA";"XFMWA";"XVM7A";...
%    "XPM9A";"XHNAA"]; % S2
%stnList = ["0PNVA";"0QNIA";"0XNZA";"1ANPA";"0ZNEA"];% S3
%stnList =["0GNUA";"0INXA";"0POKA";"03OMA";"0XNZA";"0PNVA"]; % S4
%stnList =["ZQNFA";"ZLNPA";"ZVN3A";"ZZN8A";"ZXNKA";"Z2NAA"];% S5
%stnList = ["Z2NAA";"ZXNKA";"ZVN3A";"ZZN8A";"0GNUA";"0INXA"];%S6
%stnList = ["ZXOSA";"ZQO1A";"ZRPCA";"ZZPAA";"Z3O2A";"ZYOMA";"ZROJA"];%S7
%stnList = ["ZZPAA";"Z5PHA";"Z6PPA";"0CPUA";"0GO1A";"0CO6A";"Z3O2A"];%S8
%stnList = ["YXOQA";"Y3O5A";"Y7PAA";"ZGPDA";"ZIORA";"ZCOUA";"Y3OLA";"YUOZA"];% S9
%stnList = ["YLOWA";"YUOZA";"YXOQA";"Y3OLA";"YXN9A";"YSOJA"];%S10
%stnList = ["0QNIA";"0PNVA";"0XNZA";"0ZNEA";"1ANPA"];
%stnList =["0XNZA";"03OMA";"0POKA";"0PNVA"];
%stnList = ["ZZPAA";"ZRPCA";"Z5PHA";"Z3O2A";"ZROJA";"ZQO1A";"0CO6A";...
%    "0GO1A";"ZXOSA";"ZYOMA";"0CPUA"];
%stnList = ["XVNMA";"X6NQA"];
%stnList = ["Y0MBA";"YHLWA";"Y6MAA";"Y7L9B";"Y7L9A";"Y8MAA";"Y8L8A";"Y9L7A";"Y8L6A"];
%stnList =  ["XYPWA";"YAP0A";"X3QDA";"X5QHA";"YAQGA";"YAQEA";"YCQGA";"YHP8A";"YJQBA";"YIQEA";"YKQHA"];
%stnList = ["YGNCA";"YLNBA";"YRNEA";"YUNJA";"YHNNA";"YKNVA";"YONYA";"YRNVA";"YUNZA";"Y0NZA"];
%stnList = ["XXLUA";"X1LUA";"YHLWA"];
%stnList = []

%%
% defining far apart subArrays
% stnList = ["X0K9A";"XUKWA";"XYKJA";"X2KQA";"XUKKA";"YDK3A";"YHKVA";...
%     "YGKGA";"XXLUA";"X1LUA";"XHKAA";"XBKUA";"ZZN8A";"ZVN3A";"ZLNPA";...
%     "ZXNKA";"ZQNFA";"Z2NAA";"0INXA";"0GNUA";"0GNDA"];

%% subArray F
% stnList = ["W1LKA";"XDLDA";"X0K9A";"W4L7A";"XAL4A";"XELYA";"W9MRA";"XFMHA";...
%     "XMMBA";"XFMWA";"XVMMA";"XHNAA";"XPM9A";"XVM7A";"XHNLA";"XXLUA";...
%     "X4MBA";"X1LUA"];
%% subArray E
% stnList = ["Z2MDA";"0FL9A";"0ULZA";"0GK6A";"Z8LHA";"ZRLWA";"ZILIA";"Z2KWA";...
%     "Z6KQA";"ZUJ5A";"ZOKUA";"ZDK2A";"Y8KWA";"Y0KWA"];
%% subArray Z
% stnList = ["X3QDA";"X5QHA";"YAQEA";"YAQGA";"YCQGA";"YIQEA";"YJQBA";...
%     "YHP8A";"YKQHA";"YNP9A";"YAP0A";"XYPWA";"YUP2A";"YFPTA";"XPQJA";...
%     "W7PSA";"XKPSA";"XPPNA";"XIPOA";"XGPDA"];
%%
% Also read all the stn names
stnList = unique(stnList);
[allStn] = loadSensorNames('C:\Users\soume\Dropbox\EinsteinTelescopeSurvey\TerzietBigSurvey1\MetaDataUse.txt');
stnLocs = xlsread('C:\Users\soume\Dropbox\EinsteinTelescopeSurvey\TerzietBigSurvey1\MetaDataUseNew.xlsx');
refLong = 5.9060966; refLat = 50.7513927;

%stnList = allStn;
%stnList = unique(stnList);

R = 6371000; % radius of earth in meters
for i = 1:1:length(stnList)
    stnInd = find(allStn==stnList(i,1));
    stnLocUse(i,1:2) = stnLocs(stnInd,1:2);
    stnLocUse(i,3) = stnInd;
    [xLong,yLat] = calculatedist(stnLocUse(i,1:2),[refLat,refLong],R);
    stnLocUse(i,4:5) = [xLong,yLat];
    %pairAz(i,3) = azimuth(pairNodeALatLong(1,1),pairNodeALatLong(1,2),pairNodeBLatLong(1,1),pairNodeBLatLong(1,2));
    
end

for i = 1:1:length(allStn)
    [xLong,yLat] = calculatedist(stnLocs(i,1:2),[refLat,refLong],R);
    allStnLoc(i,1:2) = [xLong,yLat];
end


% create an array of indices for storing the CCs
lList = length(stnList)-1;
for i = 1:1:(lList+1)
    ccStoreInd(((i-1)*lList+1):(i*lList),1) = i;
    ccStoreInd(((i-1)*lList+1):(i*lList),2) = [(1:(i-1))';((i+1):(lList+1))'];
end
% Also read all the stn names

nCC = (lList+1)*lList/2;
ccFullStore = zeros(1001,((lList+1)*(lList)));
ccFullStoreNumber = zeros(((lList+1)*(lList)),1);

fSamp = 25;
tArray = [(-500:1:-1),(0:1:500)]/fSamp;
% now loop
ccStoreIndNow = 1;
for stnNo = 1:1:length(stnList)
    stnA = stnList{stnNo,:};
    
    fNameA = [stnA,'.mat'];
    
    fullPathA = [dataPath,fNameA];
    if(exist(fullPathA))
        load(fullPathA);
        % convert character array to string array
        stnEnd = string(stnStore);
        endStnList = setdiff(stnList,stnA,'stable');
        % loop for other stations
        for endStnNo = 1:1:length(endStnList)
            stnInd = find(stnEnd==endStnList(endStnNo,1));
            if(~isempty(stnInd))
                ccFullStore(:,ccStoreIndNow) = ccFullStore(:,ccStoreIndNow) + ccStoreFinal(:,stnInd);
            end
            %ccTemp = ccStore(:,stnInd);
            ccStoreIndNow = ccStoreIndNow+1;
        end
        
    else
        ccStoreIndNow = ccStoreIndNow+lList;
    end
    disp('One stn done!')
end


% now time to sort the fullCCStore
ccCount = 1;
stnData = strings(nCC,2);
ccStoreFinal = [];
for i = 1:1:lList
    for j = (i+1):1:(lList+1)
        % case 1
        
        indA = find(ccStoreInd(:,1)==i);
        indB = find(ccStoreInd(:,2)==j);
        indAB = intersect(indA,indB,'stable');
        ccStoreFinal(:,ccCount) = ccFullStore(:,indAB);
        ccStoreNumber(ccCount,1) = ccFullStoreNumber(indAB,1);
        ccStoreNumber(ccCount,2:3) = [i,j];
        indA = find(ccStoreInd(:,2)==i);
        indB = find(ccStoreInd(:,1)==j);
        indBA = intersect(indA,indB,'stable');
        ccStoreFinal(:,ccCount) = ccStoreFinal(:,ccCount) + flipud(ccFullStore(:,indBA));
        ccStoreNumber(ccCount,1) = ccStoreNumber(ccCount,1) + ccFullStoreNumber(indBA,1);
        if(isnan(ccStoreFinal(1,ccCount)))
            disp('STOP');
        end
        %if(ccFullStore(indAB)~=0)
        rayAttribute(ccCount,1:2) = stnLocUse(i,4:5);
        rayAttribute(ccCount,3:4) = stnLocUse(j,4:5);
        rayAttribute(ccCount,5) = sqrt((rayAttribute(ccCount,1)-rayAttribute(ccCount,3))^2+...
            (rayAttribute(ccCount,2)-rayAttribute(ccCount,4))^2);
        rayAttribute(ccCount,6) = azimuth(stnLocUse(i,1),stnLocUse(i,2),stnLocUse(j,1),stnLocUse(j,2));
        rayAttribute(ccCount,7) = i; rayAttribute(ccCount,8) = j;
        stnData(ccCount,1) = allStn(stnLocUse(i,3),1);
        stnData(ccCount,2) = allStn(stnLocUse(j,3),1);
        %end
        %         if(ccFullStore(indBA)~=0)
        %             rayAttribute(ccCount,1:2) = stnLocUse(j,4:5);
        %             rayAttribute(ccCount,3:4) = stnLocUse(i,4:5);
        %             rayAttribute(ccCount,5) = sqrt((rayAttribute(ccCount,1)-rayAttribute(ccCount,3))^2+...
        %                        (rayAttribute(ccCount,2)-rayAttribute(ccCount,4))^2);
        %             rayAttribute(ccCount,6) = azimuth(stnLocUse(j,1),stnLocUse(j,2),stnLocUse(i,1),stnLocUse(i,2));
        %             rayAttribute(ccCount,7) = j; rayAttribute(ccCount,8) = i;
        %             stnData(ccCount,1) = allStn(stnLocUse(j,3),1);
        %             stnData(ccCount,2) = allStn(stnLocUse(i,3),1);
        %         end
        ccCount = ccCount + 1;
    end
end
% time to update the station indexes in the rayAttribute which is
% rayAttribute(i,7) and rayAttribute(i,8)
for i = 1:1:length(rayAttribute(:,1))
    stn1Ind = find(allStn==stnList(rayAttribute(i,7)));
    stn2Ind = find(allStn==stnList(rayAttribute(i,8)));
    rayAttribute(i,7) = stn1Ind;
    rayAttribute(i,8) = stn2Ind;
end

% remove NaN cross-corrs
goodInd = (~isnan(ccStoreFinal(1,:)));
ccStoreFinal = ccStoreFinal(:,goodInd);
rayAttribute = rayAttribute(goodInd,:);
stnData = stnData(goodInd,:);
% now do one thing check the fft amplitudes and if they are all balanced
fftCCAll = fft(ccStoreFinal,1001,1);
fVec = linspace(0,1,1001)*fSamp;
figure(4)
plot(fVec,abs(fftCCAll));

figure(1)
subplot(1,2,1)
% plot(allStnLoc(:,1),allStnLoc(:,2),'ko','MarkerSize',6);
hold on;
plot(stnLocUse(:,4),stnLocUse(:,5),'mo','MarkerFaceColor','m','MarkerSize',6);

%stnSeeA = "W3JWA"; stnSeeB = "XHKAA";
stnSeeA = stnList(1,1); stnSeeB = stnList(2,1);

stnSeeAInd = find(stnList==stnSeeA);stnSeeBInd = find(stnList==stnSeeB);
plot([stnLocUse(stnSeeAInd,4);stnLocUse(stnSeeBInd,4)],[stnLocUse(stnSeeAInd,5);...
    stnLocUse(stnSeeBInd,5)],'k','LineWidth',2);
hold off;

stnASeeIndices = find(ccStoreNumber(:,2)==stnSeeAInd);
stnBSeeIndices = find(ccStoreNumber(:,3)==stnSeeBInd);
stnABIntersect = intersect(stnASeeIndices,stnBSeeIndices,'stable');

%load('HdLp1HzNew.mat');
load('HdBp3_5Hz.mat');
if(isempty(stnABIntersect))
    stnASeeIndices = find(ccStoreNumber(:,3)==stnSeeAInd);
    stnBSeeIndices = find(ccStoreNumber(:,2)==stnSeeBInd);
    stnABIntersect = intersect(stnASeeIndices,stnBSeeIndices,'stable');
    ccSee = flipud(ccStoreFinal(:,stnABIntersect));
    
    %ccSee = filtfilt(HdLp1HzNew.Numerator,1,ccSee);
    ccSee = filtfilt(HdBp3_5Hz.Numerator,1,ccSee);
    %subplot(1,2,2)
    figure(3)
    plot(tArray,ccSee);
    xlim([-10,10]);
    disp(['Distance = ',num2str(rayAttribute(stnABIntersect,5)),' m']);
else
    ccSee = ccStoreFinal(:,stnABIntersect);
    %ccSee = filtfilt(HdLp1HzNew.Numerator,1,ccSee);
    ccSee = filtfilt(HdBp3_5Hz.Numerator,1,ccSee);
    %subplot(1,2,2)
    figure(2)
    plot(tArray,ccSee);
    xlim([-10,10]);
    
    disp(['Distance = ',num2str(rayAttribute(stnABIntersect,5)),' m']);
end

% make plots corresponding to 3 bandpass filters
filtFreq = [3,4,5];
for i = 1:1:3
    filtName = ['Hd',num2str(filtFreq(i)),'_',num2str(filtFreq(i)+1),'Hz.mat'];
    load(filtName);
    
    if(isempty(stnABIntersect))
        stnASeeIndices = find(ccStoreNumber(:,3)==stnSeeAInd);
        stnBSeeIndices = find(ccStoreNumber(:,2)==stnSeeBInd);
        stnABIntersect = intersect(stnASeeIndices,stnBSeeIndices,'stable');
        %ccSee = flipud(ccStoreFinal(:,stnABIntersect));
        
        ccSee = filtfilt(Hd.Numerator,1,ccSee);
        %subplot(1,2,2)
        figure(7)
        subplot(3,1,i)
        plot(tArray,ccSee);
        xlim([-10,10]);
        disp(['Distance = ',num2str(rayAttribute(stnABIntersect,5)),' m']);
    else
        ccSee = ccStoreFinal(:,stnABIntersect);
        ccSee = filtfilt(Hd.Numerator,1,ccSee);
        %subplot(1,2,2)
        figure(7)
        subplot(3,1,i)
        plot(tArray,ccSee);
        xlim([-10,10]);
        
        disp(['Distance = ',num2str(rayAttribute(stnABIntersect,5)),' m']);
    end
    
end

% load('HdBp1_5Hz.mat')
% %now filter and see which correlations are symmetric
% for i = 1:1:length(ccStoreFinal(1,:))
%     ccStoreFilt(:,i) = filtfilt(HdBp1_5Hz.Numerator,1,ccStoreFinal(:,i));
% end

for i = 1:1:length(ccStoreFinal(1,:))
    ccStoreFilt(:,i) = ccStoreFinal(:,i)/max(abs(ccStoreFinal(:,i)));
end

% for i = 1:1:length(ccStoreFinal(1,:))
%     tapOut = vel_taper2(tArray,1/fSamp,rayAttribute(i,5)/1000,0.15,1.2,0.05);
%     ccStoreFilt(:,i) = ccStoreFilt(:,i).*tapOut';
% end

% now sum the traces in distance bins
distBin = min(rayAttribute(:,5)):100:max(rayAttribute(:,5));
distBin = [distBin,max(rayAttribute(:,5))];
nBins = length(distBin(1,:));

for i = 1:1:(nBins-1)
    [ind,~] = find(rayAttribute(:,5) >= distBin(i) & rayAttribute(:,5)<distBin(i+1));
    stackedTrace(:,i) = mean(ccStoreFilt(:,ind),2,'omitnan');
    stackedTrace(:,i) = stackedTrace(:,i)/max(abs(stackedTrace(:,i)));
end
figure(30);
plotseis(stackedTrace,tArray,(distBin(1:(end-1))/1000),1);
camroll(-90);

figure(31)
surf((distBin(1:(end-1))/1000),tArray,stackedTrace);
view(2);
shading interp;
